synccomputingcode/syncsparkpy

README.md
docs/guide/start.rst

Update links in the documentation.

[PROD-738] Documentation update

---

demo/install_cli.sh
demo_emr.sh

Default to `python` if `python3` doesn't point to the right version in the installation script.

Resolve correct Python

---

sync/__init__.py
sync/awsdatabricks.py

Also publicized `get_cluster_report` method for external access.
Also tweaked timing on validation for getting cluster report (see comment).

Adjusted for cluster definition in task payload.

---

pyproject.toml
sync/__init__.py
sync/awsdatabricks.py

When attempting to apply one of our recommendations to a pre-existing Databricks job, I hit a few errors, so this is just a little PR to resolve those

Fix some errors that occur when applying cluster recommendations to DBX jobs

---

sync/__init__.py

Prepare to release new version: v0.0.10

Increment version

---

sync/__init__.py
sync/awsdatabricks.py
sync/clients/databricks.py

I think this is "ready" for review for the eventlog portion. Agent/init script logic still needs to be updated to support DBFS, though

Add DBFS support for downloading event logs

---

sync/__init__.py
sync/api/projects.py
sync/cli/__init__.py
sync/config.py

[PROD-1091](https://synccomputing.atlassian.net/browse/PROD-1091?atlOrigin=eyJpIjoiMzdkNjMwM2FiOTM0NGE2YTgxMWQwYjdhN2I5NWIxODYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PROD-1091]: https://synccomputing.atlassian.net/browse/PROD-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PROD-1091] [Databricks Conference '23] Updates to sync-cli configure command

---

sync/__init__.py
sync/api/__init__.py
sync/awsdatabricks.py
sync/awsemr.py
sync/cli/awsdatabricks.py
sync/cli/awsemr.py
sync/clients/databricks.py
sync/models.py
tests/test_awsdatabricks.py

https://synccomputing.atlassian.net/browse/PROD-1103
Adds functions and commands that report access to systems required for job integration with Sync. This will help users understand what if anything needs further configuration up-front.

[PROD-1103] Access report

---

sync/__init__.py
sync/awsdatabricks.py
sync/cli/__init__.py

https://synccomputing.atlassian.net/browse/PROD-1044
Pull out cluster update logic to the developer interface so that developers of the library don't have to duplicate it.
Also add configure command options to support unattended installation.

[PROD-1044] Refactor and CLI update for easier Airflow integration

---

sync/__init__.py
sync/api/projects.py
sync/awsdatabricks.py
sync/cli/awsdatabricks.py
sync/clients/databricks.py

https://synccomputing.atlassian.net/browse/PROD-1032
Make a best effort to delete clusters created by the library.

[PROD-1032] Actually delete the cluster

---

sync/__init__.py
sync/api/projects.py
sync/awsdatabricks.py
sync/cli/__init__.py
sync/cli/awsdatabricks.py
sync/cli/projects.py

Adds product_code parameter to functions that create projects. product_code is a new project property.

[PROD-1147] Added product_code to project creation functions

---

sync/__init__.py
sync/awsdatabricks.py

[PROD-1227](https://synccomputing.atlassian.net/browse/PROD-1227?atlOrigin=eyJpIjoiMzQzN2FlNjhiNzFjNDc0MTk2NTEyMGUxMTEzYjAyN2EiLCJwIjoiaiJ9)
[PROD-1227]: https://synccomputing.atlassian.net/browse/PROD-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-1227 Add smoke test for describe-volumes to sync-cli

---

sync/__init__.py
sync/_databricks.py

https://synccomputing.atlassian.net/browse/CUS-7
Successfully tested here: https://dbc-d95d06ca-1d00.cloud.databricks.com/?o=656201176161048#job/217634515132762/run/706222168214543

[CUS-7] Allow creating predictions for each cluster in a job run

---

sync/__init__.py
sync/api/projects.py
sync/cli/projects.py

https://synccomputing.atlassian.net/browse/PROD-1293

[PROD-1293] Add 'auto_appy_recs' property to projects

---

sync/__init__.py
sync/_databricks.py
sync/api/workspace.py
sync/cli/workspaces.py
sync/clients/sync.py

https://synccomputing.atlassian.net/browse/PROD-1282

[PROD-1282] Add workspace config attributes and update API paths

---

sync/__init__.py
sync/awsdatabricks.py

There is a bug in the library where there is a misspecification of a `Generator` type hint, where final value and errors raised was not specified. See [here](https://docs.python.org/3.6/library/typing.html#typing.Generator) for more details. 
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1648)

PROD-1648 Bugfix describe volumes

---

sync/__init__.py

Forgot to include the version bump in [the previous PR](https://github.com/synccomputingcode/syncsparkpy/pull/103l), so this PR is taking care of that
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1686)

PROD-1686 diff checker version bump

---

sync/__init__.py
sync/clients/databricks.py

Add fixie url support to proxies list for databricks client if/when necessary
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1764)

[PROD-1764] Add fixie url proxy to library

---

sync/__init__.py
sync/azuredatabricks.py
sync/config.py

Mimic changes for aws hosted on the azure side
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1779)

Prod 1779 updated sync spark py to support azure hosted

---

pyproject.toml
sync/__init__.py
sync/api/workspace.py
sync/cli/workspaces.py
sync/models.py

This updates the CLI for Creating and Updating a workspace. The cli was a bit outdated in this regard. I restructured the azure/aws fields to be dependent on compute provider, which is either implicitly discovered via the url, or prompted if they have a custom domain. 
Azure Client Id, Client Secret, Tenant Id, and Subscription Id were added to an azure hosted creation.
aws iam role arn was added for aws hosted creation.
For updating, we were already following a pattern of 'only update provided values' so i kept that going for this. Updated values will continue to be passed in as explicit flags to get updated. I intentionally left out the ability to switch between compute providers and to switch between hosting types. …

Prod 1735 update cli to allow for hosted workspace creation

---

sync/__init__.py
sync/_databricks.py
sync/errors.py

When we are unable to locate files in dbfs raise an error

[PROD-1987] Raise dbfs missing files runtime error

---

sync/__init__.py
sync/_databricks.py

Fix string interpolation where we unexpectedly treated it like a log message....
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1987) (add id)

Fix the string interpolation so its not treated like a log message

---

sync/__init__.py
sync/_databricks.py

REVERT retry logic in lib
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2007) (add id)

Prod 2007 dbfs delay extension

---

pyproject.toml
sync/clients/sync.py

Trying to avoid refreshing access tokens every time we boot the CLI.
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2252) (2252)

PROD-2252 Cache access tokens

---

sync/_databricks.py
sync/api/projects.py
sync/clients/sync.py

Building the cluster template on the BE and using that instead of generating it in the lib.
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/CUS-75)

[CUS-75] Build cluster settings from new projects/id/cluster/template API route

---

sync/clients/sync.py

Fixup auth

---

sync/__init__.py

Bump version for:
https://synccomputing.atlassian.net/browse/PROD-2109
(https://synccomputing.atlassian.net/browse/PROD-2109)

Bump version to 1.10

---

sync/__init__.py

[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2276)

[PROD-2276] bump to 1.10.1

---

sync/__init__.py
sync/_databricks.py
sync/api/projects.py
tests/clients/test_sync.py

Also fixed the return type of the function
Also fixed a type in function name (keeping the old typo in until we remove it in future)
Also fixed type issues with py3.7
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/CUS-105)

[CUS-105] handle key error when no recommendations

---

sync/__init__.py
sync/api/workspace.py
sync/cli/workspaces.py
sync/models.py

Workspace create now supports monitoring_type if collection_type is HOSTED
Workspace update now supports collection_type and monitoring_type
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2362)

[PROD-2362] Add collection_type and monitoring_type to workspace create/update

---

sync/cli/workspaces.py
sync/models.py

- Allow certain things to be passed in via the cli that previously were only could be set via an interactive prompt
- Ensure the CLI commands used in the integration test actually exit with a nonzero exit code on errors.
- Should be no real user facing changes

Changes to help with testing

---

pyproject.toml

Loosen httpx requirement

---

sync/__init__.py

Bump version

---

sync/__init__.py
sync/clients/__init__.py
sync/clients/sync.py
sync/errors.py

- Increases retries for sync api to 20
- Adds retry logic for the authentication step

Fixup retries for authentication and general

---

.github/workflows/pull-request.yml
Makefile
docs/conf.py
pyproject.toml
sync/_databricks.py
sync/api/projects.py
sync/awsdatabricks.py
sync/azuredatabricks.py
sync/cli/__init__.py
sync/cli/_databricks.py
sync/cli/projects.py
sync/cli/workspaces.py
sync/clients/__init__.py
sync/clients/cache.py
sync/clients/databricks.py
sync/clients/sync.py
sync/models.py
sync/projects.py
sync/utils/dbfs.py
tests/test_config.py

- 3.7 comparability was broken, added a couple of fixes
- Switched to ruff for linting/formatting with our standard rules
- Fixed formatting + bugs ruff picked up

Fixup with ruff + proper 3.7 compat

---

sync/__init__.py
sync/clients/sync.py

Avoid retrying forever

---

sync/__init__.py
sync/clients/sync.py

Fix infinite retrys and ensure only specific auth exceptions are retried

---

sync/__init__.py
sync/api/projects.py
sync/clients/sync.py

See https://github.com/synccomputingcode/syncsparkpy/pull/154 
Credit: @AmbientOne

Support hardware override

---

sync/__init__.py
sync/clients/databricks.py

Fix compatiblity with httpx

---

sync/models.py

Add new permission

---

pyproject.toml
sync/__init__.py

Relaxes some of the version specifiers to restrict to only major versions

Relax version specifiers + bump ver

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
pyproject.toml
sync/_databricks.py
sync/clients/__init__.py
sync/config.py
sync/models.py

Move to python 3.8
