demo/install_cli.sh

Bash doesn't like `local` outside of a function.

Demo script Bash compatibility

---

demo_emr.sh

Adding a super-simple-low-tech demo script which makes it easy for users to run a prediction using the Sync CLI. The low-tech aspect makes it easy to see the Sync CLI commands used to run a prediction, query status, and get results.
Adding logic to loop on status etc added unnecessary complexity and diminished the Sync CLI.
Keeping it super simple made the most sense.

Super simple demo script to make things easy

---

demo/install_cli.sh

Appears to be some issues with the Python 3.10 check. Disabling this for now.

Bypass Python 3.10 check

---

sync/cli/__init__.py
sync/clients/sync.py

Reverts a change to the CLI that incorrectly anticipated a web API change. Instead of,
```
% sync-cli platforms
aws-emr, aws-databricks
```
it's
```
% sync-cli products
aws-emr, aws-databricks
```
This also stops hiding "aws-databricks" which was missed in a prior PR.

Revert product list API change

---

pyproject.toml
sync/__init__.py

Hatching 1.9.0+ requires `pathspec >= 0.10.1`, but even the most recent Databricks Runtime release (DBR 13) only has `pathspec==0.9.0` installed - https://docs.databricks.com/release-notes/runtime/13.0.html#system-environment. This causes build failures when trying to `%pip install syncsparkpy` in Databricks notebooks using the most recent version of `hatchling` - 
```python
Note: you may need to restart the kernel using dbutils.library.restartPython() to use updated packages.
Collecting https://github.com/synccomputingcode/syncsparkpy/archive/main.tar.gz
Using cached https://github.com/synccomputingcode/syncsparkpy/archive/main.tar.gz
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting …
```

Pin hatchling to version 1.8.0 to fix Databricks Runtime pathspec compatibility issue

---

pyproject.toml
sync/__init__.py
sync/awsdatabricks.py
sync/cli/__init__.py
sync/cli/awsdatabricks.py
sync/clients/__init__.py
sync/clients/databricks.py
sync/clients/sync.py

First pass at allowing creation of cluster reports that may be missing instance data due to e.g. the run being too old. This adds the `--allow-incomplete` boolean flag on both `get-cluster-report` and `create-prediction` CLI commands & their associated library functions.

PROD-958 Update handling of incomplete cluster_report data for Databricks jobs

---

sync/__init__.py
sync/awsdatabricks.py
tests/test_awsdatabricks.py

Allow excluding tasks when getting a cluster report for a prediction. This allows workflow integration by tacking on a "Sync" task to record the run/create a prediction.

Allow tasks to be excluded from cluster reports

---

sync/__init__.py
sync/awsdatabricks.py
sync/cli/awsdatabricks.py
tests/test_awsdatabricks.py

This PR adds a `monitor_cluster` CLI command for Databricks that -
- Checks for a cluster log destination,
- If one exists, polls the `ec2.describes_instances` API every 30 seconds to discover instances attached to the current cluster,
- For each successful poll, dedupes the current snapshot with our previous snapshot (see - https://github.com/synccomputingcode/syncsparkpy/compare/init_scripts#diff-fcb826fa7c84469280d545c2fb63c0ad6e4d83d38a3cff66ac7cd3d4c6b0ea5eR906-R926)
- Saves each snapshot to a file `/sync_data/cluster_instances.json` in the cluster log destination directory
Then, when grabbing a cluster report, we first check if this `/sync_data/cluster_instances.json` file exists. If it does, we will include that in the cluster report. Otherwise, we will still attempt to take a …

Sync Agent `init_script`

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
demo/install_cli.sh
pyproject.toml
sync/api/predictions.py
sync/api/projects.py
sync/asyncapi/predictions.py
sync/asyncawsemr.py
sync/awsdatabricks.py
sync/awsemr.py
sync/cli/__init__.py
sync/cli/awsdatabricks.py
sync/cli/awsemr.py
sync/cli/predictions.py
sync/cli/projects.py
sync/cli/util.py
sync/clients/__init__.py
sync/clients/databricks.py
sync/clients/sync.py
sync/config.py
sync/models.py
tests/test_awsdatabricks.py
tests/test_awsemr.py

[PROD-820 Expand supported the library's Python versions to [3.7,3.11]](https://synccomputing.atlassian.net/browse/PROD-820?atlOrigin=eyJpIjoiOTIwMmJmMGFjMTc2NDdlOWIzN2QyMWUyNjdkOTMxNzMiLCJwIjoiaiJ9)
In support of running this library in customer environments, this drops the minimum supported Python version down to 3.7.x
Initially submitting this PR against the `init_scripts` branch in order to get a clean diff, but I can update the target branch to `main` once #22 is approved + merged
The main changes in this PR include -
- Changing `match` statements to `if/elif/else` chains,
- `dict`/`list`/`tuple` generic type-hints to `typing.Dict`/`List`/`Tuple`
- `Union | Types` --> `typing.Union[...]`
- Changing assignment expressions -
```python
if foo := m.get("bar"):
...
```
to -
```python
foo …
```

PROD-820 Expand supported the library's Python versions to [3.7,3.11]

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
demo/install_cli.sh
docs/guide/start.rst

`3.7.5` is not compatible with Ubuntu 22.04, but `3.7.16` is. Changes from `3.7.5` to `3.7.16` are just security patches, so there is no real functional impact to us.

Change python version in GH actions

---

sync/__init__.py
sync/api/projects.py

Allow mutating `prediction_params` of a project via the library functions instead of just the UI/API

Add prediction_params argument to create/update_project functions

---

sync/__init__.py
sync/awsdatabricks.py
sync/clients/databricks.py
sync/utils/dbfs.py
tests/test_awsdatabricks.py

[PROD-1062](https://synccomputing.atlassian.net/browse/PROD-1062?atlOrigin=eyJpIjoiOTFlN2UxMzIzYjc3NGI5Zjk2NzI5Y2ZkMGRjYjFmMzciLCJwIjoiaiJ9)
Adds support in `awsdatabricks.monitor_cluster` for saving state to DBFS, and also adds support in `awsdatabricks._get_cluster_instances` for reading back the file saved in DBFS.
[PROD-1062]: https://synccomputing.atlassian.net/browse/PROD-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PROD-1062] Add support for getting the event log from DBFS

---

sync/__init__.py
sync/awsemr.py

Should fix cluster report generation issues as discussed in - https://sync-computing.slack.com/archives/C03H8ERUPNY/p1690554169307939?thread_ts=1690553934.714369&cid=C03H8ERUPNY

Handle exhausting the next Markers for emr.list_instances/steps calls when generating an EMR cluster report

---

docs/index.rst
docs/reference/azuredatabricks.rst
pyproject.toml
sync/__init__.py
sync/_databricks.py
sync/awsdatabricks.py
sync/azuredatabricks.py
sync/cli/__init__.py
sync/cli/_databricks.py
sync/cli/awsdatabricks.py
sync/cli/azuredatabricks.py
sync/clients/databricks.py
sync/models.py

https://synccomputing.atlassian.net/browse/PROD-1176
Adds support for Azure Databricks to the library.
Basically, awsdatabricks modules were moved to _databricks and the access report, cluster report and cluster monitoring functions were moved to awsdatabricks and azuredatabricks.
An Azure Databricks cluster report with instances can be had like,
```
sync-cli azure-databricks get-cluster-report 14374
```
For Azure authentication, either set these environment variables:
```
export AZURE_TENANT_ID=069b7263-8ba5-4854-a1dd-4563b01ce1bd
export AZURE_CLIENT_ID=ed551f97-81d3-43a3-8ded-eb4972b67fb1
export AZURE_CLIENT_SECRET=# See the Sync Library app's secrets: https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Credentials/appId/ed551f97-81d3-43a3-8ded-eb4972b67fb1 …
```

[PROD-1176] Add Azure support

---

sync/__init__.py
sync/_databricks.py
sync/awsdatabricks.py
sync/models.py
tests/test_awsdatabricks.py

Add ebs volume information to the cluster report. Information is gathered via the `describe_volumes` call. This is necessary because the `describe_instances` call does not provide comprehensive information about any attached ebs storage, including the storage type, IOPS, and throughput.
To enable reusing most of the existing code without refactor I added the list of volumes as an attribute in the `instances` dict. I considered break this dict apart in the cluster report for a sense of "separation of duties", but I wasn't sure if that was any better. For example:
```
class AWSDatabricksClusterReport(DatabricksClusterReport):
instances: Union[dict, None]
volumes: Union[dict, None] #  <--- new field for volumes?
```

add ebs volume info to the cluster report

---

sync/__init__.py
sync/_databricks.py

Resolves this error when creating a prediction for an Azure Databricks run:
```
% sync-cli azure-databricks create-prediction --project bucketing_example 20258                                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                                                                                                                            
File "/Users/scottromney/.virtualenvs/syncsparkpy/bin/sync-cli", line 8, in <module> …
```

Fix 'sync-cli azure-databricks create-prediction' error

---

sync/__init__.py
sync/_databricks.py

During gradient testing, it was noticed that there are cases where it takes longer than 300 seconds for a databricks cluster to spin down. This is incompatible with the default timeout period of 300 seconds and causes submission failures for successful job completions. The timeout is now increased to 600 seconds.

Increase timeout period for get cluster state

---

sync/__init__.py
sync/_databricks.py

Manually tested:
```
>>> from sync.clients import databricks
>>> client = databricks.get_default_client()
>>> job = client.get_job("1084595443498678")
>>> from sync import _databricks
>>> x =_databricks._get_project_job_clusters(job)
>>> type(x)
<class 'dict'>
>>> x["66c7dc8f-ff02-4a3f-a14d-dbcfc31e17e0"][0]
('job_clusters', 'gradientML_sf1_static_compute')
>>> x["66c7dc8f-ff02-4a3f-a14d-dbcfc31e17e0"][1]
...
```

Fix for bug in finding job clusters

---

sync/__init__.py
sync/_databricks.py
sync/api/projects.py
sync/awsdatabricks.py
sync/azuredatabricks.py
sync/cli/projects.py
tests/test_awsdatabricks.py

Adds `cluster_path` to projects to support multi-cluster Databricks jobs. Also adds `workspace_id` to projects to help locate integration secrets for automating job/cluster onboarding. Both are optional.
With `cluster_path` we can better locate the cluster for the project which removes blockers around multi-cluster Databricks jobs.
https://synccomputing.atlassian.net/browse/PROD-1295

[PROD-1295] Use project cluster_path

---

README.md

Add info about building documentation and releasing versions to README

---

sync/__init__.py
sync/api/projects.py
sync/cli/_databricks.py
sync/cli/awsdatabricks.py
sync/cli/azuredatabricks.py
sync/clients/sync.py

Mostly just to make our lives easier.

add get-submission to the cli

---

sync/__init__.py
sync/_databricks.py

https://synccomputing.atlassian.net/browse/CB-2
Looks good with manual testing:
```
>>> from sync import awsdatabricks
>>> import logging
>>> logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s [%(name)s] %(message)s")
>>> r = awsdatabricks.create_submission_for_run(475643548716943, "Standard", "Jobs Compute", "f88a5e38-f953-48cf-b0f0-44546b10aff3")
2023-11-17 12:02:48,293 INFO [root] Waiting for cluster 1117-142827-rmf0tm5u to terminate
>>> r
Response(result='517f82c6-08a7-4390-8827-b5110d0901cd', error=None)
```

[CB-2] Fix bug in finding cluster in run

---

sync/azuredatabricks.py

Just ran into this while doing some testing. Some type annotations were incompatible with 3.7-3.10 versions of python.

make typing annotations compatible with >=3.7

---

pyproject.toml
sync/__init__.py
sync/awsdatabricks.py
sync/awsemr.py
sync/azuredatabricks.py
sync/cli/_databricks.py
sync/cli/awsemr.py
sync/cli/predictions.py
sync/cli/projects.py
sync/cli/workspaces.py
sync/clients/__init__.py
sync/utils/json.py
tests/api/test_predictions.py
tests/asyncapi/test_asyncpredictions.py
tests/test_awsdatabricks.py
tests/test_awsemr.py

Passes all current tests, tested a few of the methods that changed individually (locally) but haven't done an exhaustive test of each method. It seems like everything should be working. The package differences are the options for encoding datetimes and the fact that json.dumps is a str and orjson.dumps is bytes. The echo calls in the cli don't care if the output is bytes or strings, and all other dumps calls have been cast to bytes. The utils folder has a custom class that encodes datetimes the same as orjson.

orjson replacement with json package

---

sync/__init__.py
sync/clients/__init__.py
sync/clients/databricks.py

Add user-agent header “sync-gradient” to Databricks api call
See: “Passing HTTP User Agent Tag for REST API’s” in this doc
https://docs.google.com/document/d/1dfzbMM9bbTQ8WpasDt_B6jZzqOVJGyV5Hdo4G7KBn5Y/edit?usp=sharing
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1488) (PROD-1488)

PROD-1488: Add user-agent header to all Databricks API calls we make 

---

sync/__init__.py
sync/api/projects.py

For instance size optimization, the project models and database table now contain a new flag that holds the state of whether instance size optimization is enabled. This PR updates the library functions and endpoints that handle project creation and updates.

Update Create Project

---

.github/dependabot.yml
.github/pull_request_template.md
.gitignore
sync/__init__.py
sync/awsdatabricks.py
tests/test_awsdatabricks.py

[Relevant Design Doc](https://docs.google.com/document/d/1glmpjWbFYP9dH4Z238WXJiYPVGAssXeoGMUTeQ2I0iE/edit#heading=h.nq2pm9sc8k73)
Adding the option to pass in a dict of `filesystem` and `base_prefix` to allow overriding of the logging location for cluster monitoring
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1610)
Will test existing functionality remains.
validated retention of existing functionality by pointing our sandbox environment's init script to this branch. Ran with the logging location both to dbfs and s3.
DBFS:
s3:
pulled both files down and validated they …

implement cluster_report_destination_override

---

.gitignore
sync/__init__.py
sync/awsdatabricks.py

removed the 'home' root path from the local writing of cluster report. Expectation will be that the override contains the full path
- [ x] Relevant unit tests have been added or not applicable
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1588)

Prod-1588 edits to library monitor cluster path

---

sync/__init__.py
sync/cli/__init__.py

adding Configure back to the init method for proper file placement
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1658)

PROD-1658 bug fix cli configure

---

sync/__init__.py
sync/awsdatabricks.py

There is a bug currently in the library where a call to the `ec2.describe_volumes` only accepts at most 199 items in the `Filters` argument. However, in the case of very large clusters, there can be more than 199 instance ids passed in, which causes the call to fail. 
This PR splits the number of filters to chunks of size no more than 199. 
* All unit tests pass
* Dummy projects were kicked off on databricks and the resulting cluster was inspected with the functions calls in both the cases of small number of workers as well as number of workers > 200 and it was verified that the functions calls return the cluster volume data as expected. 
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1648)

[PROD-1648] Bugfix describe volumes

---

docs/conf.py
docs/index.rst
sync/__init__.py

The Sync library docs page has v0.0.1 in the title. However, the actual version of the Sync library is [1.4.0](https://github.com/synccomputingcode/syncsparkpy/releases/tag/v1.4.0).
https://synccomputingcode.github.io/syncsparkpy/index.html 
<title>Welcome to the Sync Library! &#8212; Sync Library 0.0.1 documentation</title>
Expected
- Version is removed from the title.
- An info box at the top of the main page shows the latest version of the library / CLI 
- For example, see [Databricks CLI page](https://docs.databricks.com/en/dev-tools/cli/index.html)
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1812) (PROD-1812)

PROD-1812: Docs Versioning

---

sync/__init__.py
sync/api/projects.py
sync/cli/projects.py
sync/projects.py
tests/test_projects.py

Adds the ability to get the latest submission's configuration for a project, and an option that specifies whether it needs to be the last successful submission, or the most recent regardless of failure. Also adds this to the CLI. Added a separate file for projects as this doesnt really fall under azure/aws databricks, and added tests as well
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1820)

Prod-1820 forma add sync library function to fetch cluster spec of latest submission in project

---

sync/__init__.py
sync/awsdatabricks.py
sync/azuredatabricks.py
tests/test_awsdatabricks.py

Adds a lambda option to the write file definition so we can write to redis from the svc library
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-1746)

Prod-1746-Hosted-Monitor-Idempotency

---

sync/__init__.py
sync/awsdatabricks.py
sync/azuredatabricks.py

Add monitor once function so we can re-enqueue instances, volumes, timelines over many celery tasks

[PROD-1968] Add monitor_once functionality to library

---

sync/__init__.py
sync/_databricks.py

bumping the dbfs polling time from 5 min to 10 min
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2007)

prod-2007-dbfs-delay-extension

---

sync/api/projects.py
tests/test_projects.py

https://github.com/synccomputingcode/sync_backend/pull/745 introduces a minor schema change to the /submissions endpoint. This updates the client to reflect that.

PROD-2106 Update submissions endpoint schema

---

sync/clients/sync.py

[PROD-2124](https://synccomputing.atlassian.net/browse/PROD-2124)
Switch to v2 endpoint so we can maintain the old endpoint for backwards compatibility
[PROD-2124]: https://synccomputing.atlassian.net/browse/PROD-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-2124 Use v2 /submissions endpoint

---

pyproject.toml
sync/clients/sync.py

- Changed the auth flow so that you can pass a CachedToken cls
- Made new class to cache token in file cache
- Made sure that the file cache works with the lowest py version that we support, py 3.7 
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2276)

[PROD-2276] Add new class to cached auth token to file (or redis with subclass)

---

sync/__init__.py
sync/clients/cache.py
sync/clients/sync.py

cache.py should be safe to import without breaking the rest.
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2276)

[PROD-2276] Move CachedToken class to not break globals and imports

---

sync/_databricks.py

The while loop for azure eventlog retrieval is never entered because eventlog_response is populated after the first call.

EBF: Enable azure retries 

---

pyproject.toml
sync/__init__.py

customer got issue with strict pinning.
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2324)

[PROD-2324] pin python-dateutil<3 to be less restrictive

---

sync/azuredatabricks.py

Occasionally, when the dbx api would fail for miscellaneous reasons, we would enter a section of code on cluster creation that was causing an exception. I've fixed the exception but would like to note that this code path will no longer yield a submission because we'll be missing an instance timeline and the other sync-specific information. It's no longer sufficient for us to grab a best guess snapshot. Should we keep this code in here so we at least get all available data in the cluster report saved to s3 or should we take these code paths out for aws/azure because this cluster report is deprecated?
[Related Jira Ticket](https://synccomputing.atlassian.net/browse/PROD-2005)
Add any relevant testing examples or …

fix cluster report creation bug

---

sync/clients/sync.py

Avoid refreshing token each request

---

sync/__init__.py
sync/clients/sync.py

Adds library access to the `hardware-override-aws` endpoint.

PROD-2618 add endpoint access for hardware override
